name: fluttercommerce
description: Shopping UI design in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  country_pickers: ^1.1.0
  flutter_icons: ^0.2.5
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  division: ^0.6.1
  page_transition: '^1.1.0'
  bottom_navy_bar: ^5.1.0
  sliding_up_panel: ^0.3.4
  flutter_xlider: ^3.4.0
  intro_views_flutter: ^2.6.0
  rflutter_alert: ^1.0.3
  hidden_drawer_menu: ^1.1.2
  file_picker: ^1.4.3+2 
  http: ^0.13.0
  sharedpreference: ^0.0.1
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4+4
  dio: ^4.0.4
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf
